nelmio_api_doc:
    documentation:
        host: localhost:8000
        schemes: [http, https]
        info:
            title: API Boilerplate
            description: Rest API using Symfony 4.2!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
